# Generated by Django 3.2.4 on 2021-07-13 21:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_alter_relfection_reflection'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Relfection',
            new_name='Reflection',
        ),
    ]
