# Generated by Django 3.2.4 on 2021-07-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_relfection_reflection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='details',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
    ]
